### ISSUE TITLE
if cmake finds qt5, it is impossible to switch to not using qt5 (e.g. if i want to use qt4)

### ISSUE THREAD

**Issue by andsok75** [acfr/snark#87]
on a clean build on ubuntu 14.04:
- run ccmake ~/src/snark; configure, observe the error (see below)
- switch off snark_use_Qt5, run cmake
- build, observe compilation errors (see below)

CMAKE ERROR:

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
   Could not find a package configuration file provided by "Qt53D" with any of
   the following names:

```
 Qt53DConfig.cmake
 qt53d-config.cmake
```

   Add the installation prefix of "Qt53D" to CMAKE_PREFIX_PATH or set
   "Qt53D_DIR" to a directory containing one of the above files.  If "Qt53D"
   provides a separate development package or SDK, be sure it has been
   installed.
 Call Stack (most recent call first):
   graphics/CMakeLists.txt:18 (FIND_PACKAGE)

COMPILATION ERRORS

/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:15:2: error: #error "This file was generated using the moc from 5.2.1. It"
 #error "This file was generated using the moc from 5.2.1. It"
  ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:16:2: error: #error "cannot be used with the include files from this version of Qt."
 #error "cannot be used with the include files from this version of Qt."
  ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:17:2: error: #error "(The moc has changed too much.)"
 #error "(The moc has changed too much.)"
  ^
Linking CXX executable ../../bin/stereo-demo
Linking CXX static library ../../lib/libsnark_hokuyo.a
[ 49%] Built target stereo-demo
[ 50%] Building CXX object sensors/velodyne/CMakeFiles/snark_velodyne.dir/scan_tick.cpp.o
[ 50%] Built target snark_hokuyo
Scanning dependencies of target hokuyo-to-csv
[ 50%] Building CXX object sensors/hokuyo/applications/CMakeFiles/hokuyo-to-csv.dir/hokuyo-to-csv.cpp.o
[ 50%] /home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:22:5: error: ‘QByteArrayData’ does not name a type
     QByteArrayData data[3];
     ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:28:24: error: ‘QByteArrayData’ was not declared in this scope
         - idx \* sizeof(QByteArrayData) \
                        ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:32:1: note: in expansion of macro ‘QT_MOC_LITERAL’
 QT_MOC_LITERAL(0, 0, 27),
 ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:29:5: error: ‘Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET’ was not declared in this scope
     )
     ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:32:1: note: in expansion of macro ‘QT_MOC_LITERAL’
 QT_MOC_LITERAL(0, 0, 27),
 ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:28:24: error: ‘QByteArrayData’ was not declared in this scope
         - idx \* sizeof(QByteArrayData) \
                        ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:33:1: note: in expansion of macro ‘QT_MOC_LITERAL’
 QT_MOC_LITERAL(1, 28, 16),
 ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:29:5: error: ‘Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET’ was not declared in this scope
     )
     ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:33:1: note: in expansion of macro ‘QT_MOC_LITERAL’
 QT_MOC_LITERAL(1, 28, 16),
 ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:28:24: error: ‘QByteArrayData’ was not declared in this scope
         - idx \* sizeof(QByteArrayData) \
                        ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:34:1: note: in expansion of macro ‘QT_MOC_LITERAL’
 QT_MOC_LITERAL(2, 45, 0)
 ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:29:5: error: ‘Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET’ was not declared in this scope
     )
     ^
/home/segway/code/build/snark/graphics/qt3d/moc_view.cxx:34:1: note: in expansion of macro ‘QT_MOC_LITERAL’
...
